project:
  type: website
  output-dir: docs

website:
  title: "Nando's MDS Notes"
  navbar:
    logo: images/mds_logo.png
    left:
      - href: index.qmd
      - list.qmd
  favicon: images/white_cartoon.PNG

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
